# Lab 3 - Data Cleaning

## 1. Profile Missingness

In this section, we identify missing values in each column.

We calculate both the number of missing values and the percentage of missing values for every column.

In [1]:
import pandas as pd
df = pd.read_csv("/Users/agam/Desktop/pythonAssignment/week_challenge/samples/file1.csv")
df.head()

       Name  Age Country  Revenue        Date
0      Agam   19   India     1200  2026-08-01
1  Divanshu   19   India     1500  2026-08-03
2     Anish   21  Canada      900  2026-08-05
3     Rahul   20     USA     2100  2026-08-07
4     Priya   22   India     1800  2026-08-10

## Missing Value Count

We calculate the total number of missing values in each column.

In [2]:
df.isna().sum()

Name       0
Age        0
Country    0
Revenue    0
Date       0
dtype: int64

## Missing Value Percentage

We calculate the percentage of missing values in each column to understand how much data is missing.

In [3]:
mis_per = df.isna().mean() * 100
mis_per

Name       0.0
Age        0.0
Country    0.0
Revenue    0.0
Date       0.0
dtype: float64

## 2. Missing Value Strategy

We choose a missing-value strategy for each column based on the observed missingness.

- **Name:** Leave unchanged because there are no missing values.
- **Age:** Leave unchanged because there are no missing values.
- **Country:** Leave unchanged because there are no missing values.
- **Revenue:** Leave unchanged because there are no missing values.
- **Date:** Leave unchanged because there are no missing values.

**Overall strategy:** Leave all columns unchanged because the dataset contains no missing values.

In [9]:
df.dropna()

       Name  Age Country  Revenue        Date
0      Agam   19   India     1200  2026-08-01
1  Divanshu   19   India     1500  2026-08-03
2     Anish   21  Canada      900  2026-08-05
3     Rahul   20     USA     2100  2026-08-07
4     Priya   22   India     1800  2026-08-10

## 3. Fix Wrong Data Types

We inspect the data types of all columns and convert columns to appropriate data types where necessary.

The `Date` column should be stored as a datetime type so that dates can be sorted, filtered, and analyzed correctly.

In [10]:
df.dtypes

Name         str
Age        int64
Country      str
Revenue    int64
Date         str
dtype: object

### Convert Date to Datetime

The `Date` column is converted from text format to datetime format.

In [11]:
df["Date"] = pd.to_datetime(df["Date"])

In [13]:
df.dtypes

Name                  str
Age                 int64
Country               str
Revenue             int64
Date       datetime64[us]
dtype: object

## 4. Check Duplicates and Outliers

In this section, we check for duplicate rows and potential outliers in the numeric columns.

In [14]:
df.duplicated().sum()

np.int64(0)

### Outlier Check

We inspect the numeric columns for unusually high or low values using summary statistics and a boxplot.

In [15]:
df[["Age", "Revenue"]].describe()

            Age      Revenue
count   5.00000     5.000000
mean   20.20000  1500.000000
std     1.30384   474.341649
min    19.00000   900.000000
25%    19.00000  1200.000000
50%    20.00000  1500.000000
75%    21.00000  1800.000000
max    22.00000  2100.000000

## 5. Confirm Data Consistency

We confirm that the cleaned data contains no unexpected missing values and that the numeric columns have sensible ranges.

In [16]:
df.isna().sum()

Name       0
Age        0
Country    0
Revenue    0
Date       0
dtype: int64

In [17]:
df[["Age", "Revenue"]].describe()

            Age      Revenue
count   5.00000     5.000000
mean   20.20000  1500.000000
std     1.30384   474.341649
min    19.00000   900.000000
25%    19.00000  1200.000000
50%    20.00000  1500.000000
75%    21.00000  1800.000000
max    22.00000  2100.000000