# Lab 1 - Pandas Fundamentals

## 1. Load and Inspect the CSV

In this section, we load the CSV file into a pandas DataFrame and inspect the dataset using:

- `head()` to view the first few rows

In [5]:
import pandas as pd
df = pd.read_csv("/Users/agam/Desktop/pythonAssignment/week_challenge/samples/file1.csv")
df.head()

       Name  Age Country  Revenue        Date
0      Agam   19   India     1200  2026-08-01
1  Divanshu   19   India     1500  2026-08-03
2     Anish   21  Canada      900  2026-08-05
3     Rahul   20     USA     2100  2026-08-07
4     Priya   22   India     1800  2026-08-10

## Inspect Dataset Information

The `info()` method provides information about the DataFrame, including:

- Column names
- Number of non-null values
- Data types
- Memory usage

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Age      5 non-null      int64
 2   Country  5 non-null      str
 3   Revenue  5 non-null      int64
 4   Date     5 non-null      str
dtypes: int64(2), str(3)
memory usage: 332.0 bytes

## Summary Statistics

The `describe()` method provides summary statistics for the numeric columns in the DataFrame.

It includes:

- Count
- Mean
- Standard deviation
- Minimum value
- 25th percentile
- Median
- 75th percentile
- Maximum value

In [9]:
df.describe()

            Age      Revenue
count   5.00000     5.000000
mean   20.20000  1500.000000
std     1.30384   474.341649
min    19.00000   900.000000
25%    19.00000  1200.000000
50%    20.00000  1500.000000
75%    21.00000  1800.000000
max    22.00000  2100.000000

## Dataset Shape

The `shape` attribute returns the number of rows and columns in the DataFrame.

The result is returned in the format:

`(rows, columns)`

In [10]:
df.shape

(5, 5)

## 2. Select Rows and Columns

In this section, we use `loc` and `iloc` to select specific rows and columns from the DataFrame.

We also use Boolean filtering to select rows based on a condition.

### Select Specific Columns

We can select one or more columns from a DataFrame by using the column names.

In [11]:
df[["Name","Age","Revenue"]]

       Name  Age  Revenue
0      Agam   19     1200
1  Divanshu   19     1500
2     Anish   21      900
3     Rahul   20     2100
4     Priya   22     1800

### Select Rows and Columns Using `loc`

The `loc` method selects data using row and column labels.

In [12]:
df.loc[0:2,["Name","Age","Revenue"]]

       Name  Age  Revenue
0      Agam   19     1200
1  Divanshu   19     1500
2     Anish   21      900

### Select Rows and Columns Using `iloc`

The `iloc` method selects data using integer-based row and column positions.

In [13]:
df.iloc[0:3,0:3]

       Name  Age Country
0      Agam   19   India
1  Divanshu   19   India
2     Anish   21  Canada

### Filter Rows Using a Boolean Condition

Boolean filtering allows us to select only the rows that satisfy a condition.

Here, we select rows where `Age` is greater than 19.

In [14]:
df[df["Age"]>19]

    Name  Age Country  Revenue        Date
2  Anish   21  Canada      900  2026-08-05
3  Rahul   20     USA     2100  2026-08-07
4  Priya   22   India     1800  2026-08-10

## 3. Create a Derived Column

A new column can be created from existing columns.

In this section, we create a `Revenue_per_Age` column by dividing `Revenue` by `Age`.

In [15]:
df["Revenue_Age"]=df["Revenue"]/df["Age"]
df.head()

       Name  Age Country  Revenue        Date  Revenue_Age
0      Agam   19   India     1200  2026-08-01    63.157895
1  Divanshu   19   India     1500  2026-08-03    78.947368
2     Anish   21  Canada      900  2026-08-05    42.857143
3     Rahul   20     USA     2100  2026-08-07   105.000000
4     Priya   22   India     1800  2026-08-10    81.818182

### Derived Column Result

The new `Revenue_Age` column is calculated using the existing `Revenue` and `Age` columns.

In [19]:
df[["Name", "Revenue", "Age", "Revenue_Age"]]

       Name  Revenue  Age  Revenue_Age
0      Agam     1200   19    63.157895
1  Divanshu     1500   19    78.947368
2     Anish      900   21    42.857143
3     Rahul     2100   20   105.000000
4     Priya     1800   22    81.818182

## 4. Group By and Aggregate

In this section, we group the data by the categorical `Country` column.

We calculate the mean and count of the `Revenue` column for each country.

In [21]:
df.groupby("Country")["Revenue"].agg(["mean","count"])

           mean  count
Country
Canada    900.0      1
India    1500.0      3
USA      2100.0      1

## 5. Merge Two DataFrames

In this section, we create a second DataFrame and merge it with the original DataFrame using the `Name` column.

We then check the resulting row count to make sure the merge produced the expected number of rows.

In [23]:
dept=pd.DataFrame({
    "Name":["Agam","Divanshu","Anish","Rahul","priya"],
    "Department":["Cse","Cse","Cse","Cse","It"]
})
dept

       Name Department
0      Agam        Cse
1  Divanshu        Cse
2     Anish        Cse
3     Rahul        Cse
4     priya         It